mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.202.65.25:3306/testdb?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations:
        - classpath:sql/schema.sql
      data-locations:
        - classpath:sql/data.sql
      platform: mysql
      encoding: UTF-8
      mode: always