DROP TABLE IF EXISTS T_USER;

CREATE TABLE T_USER (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    AGE VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO T_USER(USERNAME, AGE) VALUES('zhangsan','18');

INSERT INTO T_USER(USERNAME, AGE) VALUES('lisi','20');

INSERT INTO T_USER(USERNAME, AGE) VALUES('wangwu','22');