DROP TABLE IF EXISTS T_USER;

CREATE TABLE T_USER (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    AGE VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO T_USER(USERNAME, AGE) VALUES('张三','18');

INSERT INTO T_USER(USERNAME, AGE) VALUES('李四','20');

INSERT INTO T_USER(USERNAME, AGE) VALUES('王五','22');